accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from . import views

Logout = LogoutView.as_view()

app_name = 'accounts'

urlpatterns = [

    path('signup/', views.UserRegistration, name = 'signup'),
    path('login/', views.UserLogin, name = 'login'),
    path('logout/', Logout, name='logout'),

    #path('resend_verify_email/', views.ResendMail, name = 'resend'),
    path('<pk>/verify/<token>/', views.UserVerification, name = 'verify'),
    
    #path('password/', views.change_password, name = 'change_password'), 
    path('user_update/', views.update_user, name = 'user_update'),
    #path('upload_profile/', views.upload_profile, name = 'upload_profile')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('sociallogin/', include('allauth.urls')),
    path('posts/',include('posts.urls',namespace="posts")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('',views.index,name="index"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from . import views


app_name = 'posts'
urlpatterns = [
    path('',views.posts_home,name='posts_home'),
    path('<int:post_id>/',views.posts_detail,name="posts_detail"),
    path('new/',views.posts_new,name="posts_new"),
    path('postslist/<str:name>/<str:slug>/',views.posts_list,name="posts_list"),
    #path('create/',views.post_create,name="post_create"),
    path('like/', views.posts_like, name='posts_like'),
    path('addcomment/<int:post_id>/',views.posts_add_comment,name='posts_add_comment'),
    path('remove/<int:comment_id>/',views.posts_remove_comment,name='posts_remove_comment'),
   # path('approve/<int:comment_id>/',views.posts_approve_comment,name='posts_approve_comment'),
    path('delete/<int:post_id>/',views.posts_delete,name='posts_delete'),
    path('edit/<int:post_id>/',views.posts_edit,name='posts_edit'),
    path('commentedit/<int:comment_id>/',views.posts_edit_comment,name="posts_edit_comment"),
    path('postssearch/',views.posts_search,name="posts_search"),
    path('mypost/',views.posts_my,name="posts_my"),
    #path('commnetlike/',views.comment_like,name='comment_like'),
]

posts/models.py
# Create your models here.
from django.db import models
from django.conf import settings
#from django.contrib.auth.models import User
#from django.contrib import auth
from ckeditor_uploader.fields import RichTextUploadingField


class TimeStampedModel(models.Model):
    """Base Model"""
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True



class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey('self',blank=True, null=True ,related_name='children',on_delete=models.PROTECT)

    class Meta:
        unique_together = ('slug', 'parent',)    #enforcing that there can not be two
        verbose_name_plural = "categories"       #categories under a parent with same 
                                                 #slug 

    def __str__(self):                           # __str__ method elaborated later in
        full_path = [self.name]                  # post.  use __unicode__ in place of
                                                 # __str__ if you are using python 2
        k = self.parent                          

        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])

class Comment(TimeStampedModel):
    post = models.ForeignKey('Post',null=True,on_delete=models.CASCADE,related_name='comments')
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        null=True, 
        related_name='comment',
        verbose_name='글쓴이',
        )
    body = RichTextUploadingField()
    #approved_comment = models.BooleanField(default=False)
    #commentlikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='commentlikes',blank=True)

    def __str__(self):
        return self.post.title

    def approve(self):
        self.approved_comment = True
        self.save()
    #@property
    #def total_likes(self):
    #    return self.commentlikes.count() #likes 컬럼의 값의 갯수를 센다

class Post(TimeStampedModel):
    title = models.CharField(max_length=100)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        null=True, 
        related_name='post',
        verbose_name='글쓴이',
        )
    body = RichTextUploadingField()
    category = models.ForeignKey('Category', null=True, blank=False,on_delete=models.PROTECT)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes')

    def __str__(self):
        return self.title

    def get_cat_list(self):           #for now ignore this instance method,
        k = self.category
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent

        for i in range(len(breadcrumb)-1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        return breadcrumb[-1:0:-1]

    @property
    def total_likes(self):
        return self.likes.count() #likes 컬럼의 값의 갯수를 센다

    @property
    def comments_count(self):
        return self.comments.count()

posts/forms.py
from django import forms
from .models import Post , Category ,Comment
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from ckeditor_uploader.fields import RichTextUploadingField
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from operator import is_not
from functools import partial
# Register your models here.

def min_length_3_validator(value):
    if len(value) < 3:
        raise forms.ValidationError('3글자 이상 입력해 주세요.')

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title','body','category']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.exclude(parent__isnull=True)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

posts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect , get_list_or_404
from django.http import HttpResponse
from django.views.decorators.http import require_GET, require_POST
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator
from .forms import PostForm,CommentForm
from .models import Post,Category,Comment
from django.template.defaultfilters import slugify
import datetime
try:
    from django.utils import simplejson as json
except ImportError:
    import json
# Create your views here.

def index(request):
    return render(request,'index.html')

def posts_home(request):
    category_list = Category.objects.all()
    return render(request,"posts_categories.html",{'categories':category_list,'user':request.user})

def posts_list(request,name,slug):
    categories = Category.objects.all()
    if name == 'open':
        open_category = get_object_or_404(Category,slug=slug)
        for x in categories:
            if x.name=='pro' and x.parent == open_category.parent:
                pro_category = get_object_or_404(Category,slug=x.slug)
        posts_list = Post.objects.filter(category=open_category)
        paginator = Paginator(posts_list,10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)
    if name == 'pro':
        pro_category = get_object_or_404(Category,slug=slug)
        for x in categories:
            if x.name =='open' and x.parent == pro_category.parent:
                open_category = get_object_or_404(Category,slug=x.slug)
        posts_list = Post.objects.filter(category=pro_category)
        paginator = Paginator(posts_list,10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)
    return render(request,'posts_list.html',{'posts':posts,'opencategory':open_category,'procategory':pro_category,'categories':categories})

def posts_search(request):
    #모든 카테고리 가져오기
    categories = Category.objects.all()
    # 검색할 분야 찾기
    slug = request.GET['categoryslug']
    category = get_object_or_404(Category,slug=slug)

    #openboard 검색
    if category.name == 'open':
        open_category = get_object_or_404(Category,slug=slug)
        for x in categories:
            if x.name=='pro' and x.parent == open_category.parent:
                pro_category = get_object_or_404(Category,slug=x.slug)
        # 검색 쿼리셋 가져오기
        qs = Post.objects.filter(category=open_category)
        ps=''
        rs=''
        q = request.GET.get('q','')

        if q: # q가 있으면
            ps = qs.filter(title__icontains=q) # 제목에 q가 포함되어 있는 레코드만 필터링
            rs = qs.filter(body__icontains=q) # 내용에 q가 포함되어 있는 레코드만 필터링 
            qs = ps | rs  # 쿼리셋 합치기 
        paginator = Paginator(qs,10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)
    
    #professional board 검색
    if category.name == 'pro':
        pro_category = get_object_or_404(Category,slug=slug)
        for x in categories:
            if x.name =='open' and x.parent == pro_category.parent:
                open_category = get_object_or_404(Category,slug=x.slug)
        # 검색 쿼리셋 가져오기
        qs = Post.objects.filter(category=pro_category)
        ps=''
        rs=''
        q = request.GET.get('q','')

        if q: # q가 있으면
            ps = qs.filter(title__icontains=q) # 제목에 q가 포함되어 있는 레코드만 필터링
            rs = qs.filter(body__icontains=q) # 내용에 q가 포함되어 있는 레코드만 필터링 
            qs = ps | rs  # 쿼리셋 합치기 

        paginator = Paginator(qs,10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)
    return render(request,'posts_list.html',{'posts':posts,'opencategory':open_category,'procategory':pro_category,'categories':categories})

def posts_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            post.creator = request.user
            post.save()
            return redirect('/posts/'+str(post.id))
    else:
        form = PostForm()
    return render(request,'posts_new.html',{'form':form})

def posts_edit(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    if request.method =='POST':
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('/posts/'+str(post.id))
    else:
        form = PostForm(instance=post)
    return render(request,'posts_new.html',{'form':form})

def posts_detail(request,post_id):
    post_detail = get_object_or_404(Post,pk=post_id)
    request_user = request.user
    return render(request,'posts_detail.html',{'post':post_detail,'user':request_user})

@login_required
@require_POST
def posts_like(request):
    if request.method == 'POST':
        user = request.user # 로그인한 유저를 가져온다.
        post_id = request.POST.get('pk', None)
        post = Post.objects.get(pk = post_id) #해당 메모 오브젝트를 가져온다.

        if post.likes.filter(id = user.id).exists(): #이미 해당 유저가 likes컬럼에 존재하면
            post.likes.remove(user) #likes 컬럼에서 해당 유저를 지운다.
            message = '좋아요를 취소했습니다.'
        else:
            post.likes.add(user)
            message = '좋아요를 추가했습니다.'

    context = {'likes_count' : post.total_likes, 'message' : message}
    return HttpResponse(json.dumps(context), content_type='application/json')

def posts_add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.creator = request.user
            comment.save()
            return redirect('/posts/'+str(post.id))
    else:
        form = CommentForm()
    return render(request, 'posts_add_comment.html', {'form': form,'post':post})

@login_required
def posts_edit_comment(request,comment_id):
    comment = get_object_or_404(Comment,pk=comment_id)
    if request.method == 'POST':
        form = CommentForm(request.POST,instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('/posts/'+str(comment.post.id))
    else:
        form = CommentForm(instance=comment)
    return render(request,'posts_add_comment.html',{'form':form,'post':comment.post})

#@login_required
#def posts_approve_comment(request, comment_id):
#    comment = get_object_or_404(Comment, pk=comment_id)
#    comment.approve()
#    return redirect('/posts/'+str(comment.post.id))

@login_required
def posts_remove_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('/posts/'+str(comment.post.id))

@login_required
def posts_delete(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    post.delete()
    return redirect('/posts/')

def posts_my(request):
    user = request.user #로그인한 유저
    posts_list = Post.objects.filter(creator = user)

    paginator = Paginator(posts_list,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    return render(request,'posts_my.html', {'posts' : posts ,'posts_list' : posts_list})

def posts_mycomment(request):
    user = request.user #로그인한 유저
    posts_list = Post.objects.filter(creator = user)

    paginator = Paginator(posts_list,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    return render(request,'posts_mycomment.html', {'posts' : posts ,'posts_list' : posts_list})

#@login_required
#@require_POST
#def comment_like(request):
#    if request.method == 'POST':
#        user = request.user # 로그인한 유저를 가져온다.
#        comment_id = request.POST.get('pk', None)
#        comment = Comment.objects.get(pk = comment_id) #해당 메모 오브젝트를 가져온다.

#        if comment.commentlikes.filter(id = user.id).exists(): #이미 해당 유저가 likes컬럼에 존재하면
#            comment.commentlikes.remove(user) #likes 컬럼에서 해당 유저를 지운다.
#            message = '좋아요를 취소했습니다.'
#        else:
#            comment.commentlikes.add(user)
#            message = '좋아요를 추가했습니다.'

#    context = {'likes_count' : comment.total_likes, 'message' : message}
#    return HttpResponse(json.dumps(context), content_type='application/json')

def show_category(request,hierarchy= None):
    category_slug = hierarchy.split('/')
    category_queryset = list(Category.objects.all())
    all_slugs = [ x.slug for x in category_queryset ]
    parent = None
    for slug in category_slug:
        if slug in all_slugs:
            parent = get_object_or_404(Category,slug=slug,parent=parent)
        else:
            instance = get_object_or_404(Post, slug=slug)
            breadcrumbs_link = instance.get_cat_list()
            category_name = [' '.join(i.split('/')[-1].split('-')) for i in breadcrumbs_link]
            breadcrumbs = zip(breadcrumbs_link, category_name)
            return render(request, "posts_detail.html", {'instance':instance,'breadcrumbs':breadcrumbs})

    return render(request,"posts_categories.html",{'post_set':parent.post_set.all(),'sub_categories':parent.children.all()})

posts/templates/index.html
<!--
<a href="#"><h1> Demoon </h1></a>
<br> <br>

<p> 로그인 하세요! </p>
<a href="{% url 'accounts:login'%}"><p> 로그인</p></a> <br>
<a href="{% url 'accounts:signup'%}"><p>회원가입</p></a> <br>
-->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  <title>Document</title>
  <style>


body{
  background: #000;
  display: flex;
  text-align: center;
}

.main{
  position:fixed;
  top:0;
  left:0;
  background-image:url(/static/img/starry.jpg);
  -webkit-background-size:/*@@prefixmycss->No equivalent*/;
  -moz-background-size:cover;
  -o-background-size:/*@@prefixmycss->No equivalent*/;
  background-size:cover;
  display:block;
  width:100%;
  height:100%;

}

.light{
  font-size: 1rem;
  font-family: 'Lato', sans-serif;
  margin: 0 auto;
  margin-top: 5vh;

}

.light div{
  display: block;
  vertical-align: center;
  animation: animate 20s ease-in-out 1;
  margin: 0 auto;
  padding: 0;
  position: relative;
  color: #111;
}
.logo{
  display: block;
  vertical-align: center;
  animation: animate 20s ease-in-out 1;
  margin: 0 auto;
  padding: 0;
  position: relative;
  color: #111;
}



.light div:nth-child(1){
  animation-delay: 0s;
}
.light div:nth-child(2){
  animation-delay: .25s;
}
.light div:nth-child(2){
  animation-delay: .5s;
}
.light div:nth-child(3){
  animation-delay: .75s;
}
.light div:nth-child(4){
  animation-delay: 1.25s;
}
.light div:nth-child(5){
  animation-delay: 1.25s;
}
.light div:nth-child(6){
  animation-delay: 1.5s;
}
.light div:nth-child(7){
  animation-delay: 1.75s;
}




@keyframes animate {
20%, 100%{
    color: #fff;
    text-shadow: 0 0 5px #fff,
      0 0 20px #fff,
      0 0 40px #fff,
      0 0 80px #fff,
      0 0 120px #fff,
      0 0 200px #fff,
      0 0 300px #fff,
      0 0 400px #fff;
  }
}

button {
  margin: 12px;
}
.btn-default {
  background-color: #000;
  color: #000;
}
.btn-primary {
  background-color:
    #000;
  color: #000;
}

@keyframes glowing {
  0% { box-shadow: 0 0 -10px #fff; }
  40% { box-shadow: 0 0 20px #fff; }
  60% { box-shadow: 0 0 20px #fff; }
  100% { box-shadow: 0 0 -10px #fff; }
}

.button-glow {
  animation: glowing 5000ms infinite;
}
  </style>
</head>
<body>

<div class="main">

  <div class="logo" style=" background-image: url(/static/img/logo.png); background-repeat: no-repeat;
  background-position: center;
  box-sizing: border-box;
  background-size: contain;width:20%; height: 80px; margin: 0 auto;   margin-top: 20vh;"></div>

  <div class="light">
  <div>의심의 저편에서 진리가 탄생하는 이치는</div>
  <br>
  <div>어둠에서 빛이 탄생하는 허위의 이치와</div>
  <br>
  <div>같은 관계를 가지고 있다.</div>
  <br>
  <button type="button" class="btn btn-lg btn-link button-glow" style="width:20%; height: 40px;  border-radius: 3px; background: transparent; color:#fff;"><a href="{% url 'accounts:login'%}" style="color:#fff; text-decoration:none;" >Log in</a></button>
  <br>
    <button type="button" class="btn btn-lg btn-link button-glow" style="width:20%; height:40px;  border-radius: 3px; background: transparent; color:#fff;"><a href="{% url 'accounts:signup'%}" style="color:#fff; text-decoration:none;">Create Account</a></button>

</div>
</body>
</html>

posts/templates/posts_add_comment.html
    <a href="{% url 'posts:posts_home'%}"><h1>daemoon</h1></a><br>
    <h1>답변하기</h1> <br>

    <p>질문내용</p>
    <p>제목: {{post.title}}</p> <br>
    <p>본문: {{post.body|safe}} </p>

    <form method="POST" class="post-form">{% csrf_token %}
        {{form.media}}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">답변하기</button>
    </form>

posts/templates/posts_detail.html
{% extends 'base.html'%}

{% block title%}
<title> daemoon</title>
{% endblock%}
{% block content %}

<h1> {{post.title}} </h1>
<!--삭제 업데이트 버튼-->
{%if user == post.creator %}
<a href="{% url 'posts:posts_delete' post.id %}"><p>삭제하기</p></a>
<a href="{% url 'posts:posts_edit' post.id %}"><p>수정하기</p></a>
{% endif%}
<div style="background-size: contain;">
{{post.body|safe}}
</div>
{{post.created_at}}
<!-- post 좋아요 버튼-->
      <input type="button" class="like" name="{{ post.id }}" value="Like">
      <p id="count{{ post.id }}">count : {{ post.total_likes }}</p>
<!--post 좋아요 버튼 끝-->
<a class="btn btn-default" href="{% url 'posts:posts_add_comment' post.id %}">댓글 추가하기</a>
{% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
            {{ comment.created_at }}
            {% if comment.creator == user %}
                <a class="btn btn-default" href="{% url 'posts:posts_remove_comment' comment.id %}"><span class="glyphicon glyphicon-remove">답변제거</span></a>
                <a class="btn btn-default" href="{% url 'posts:posts_edit_comment' comment.id %}"><span class="glyphicon glyphicon-ok">답변수정</span></a>
            {% endif %}
        </div>
        <strong>{{ comment.creator.name }}</strong>
        <p>{{ comment.body|safe }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}


<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
// 좋아요 버튼 처리
// 버튼 클릭 > ajax통신 (like url로 전달) > views의 like 메소드에서 리턴하는 값 전달받기 > 성공시 콜백 호출
$('.like').click(function(){
  var pk = $(this).attr('name') // 클릭한 요소의 attribute 중 name의 값을 가져온다.
  $.ajax({
      type: "POST", // 데이터를 전송하는 방법을 지정한다.
      url: "{% url 'posts:posts_like' %}", // 통신할 url을 지정한다.
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터를 전송할 때 이 옵션을 사용한다.
      dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정한다. 없으면 알아서 판단한다.
      // 서버측에서 전송한 데이터 views.py like 메소드
      // context = {'likes_count' : memo.total_likes, 'message' : message}
      // json.dump(context)를 통해서 json 형식으로 전달된다.

      success: function(response){ // 성공했을 때 호출할 콜백을 지정한다.
        id = $(this).attr('name')
        $('#count'+ pk).html("count : "+ response.likes_count);
        alert(response.message);
      },
      error:function(request,status,error){
        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
  });
})
</script>
{% endblock %}

posts/templates/posts_list.html
{% extends 'base.html'%}

{% block title%}
<title> daemoon</title>
{% endblock%}
{% block content %}

<a href="{% url 'posts:posts_new' %}" style="color:black;"><p> 글 쓰기 </p> </a>
<a href="{% url 'posts:posts_list' 'open' opencategory.slug %}"><p> openboard </p></a>
<a href="{% url 'posts:posts_list' 'pro' procategory.slug %}"> <p>professional board</p> </a>
<!--search form-->

<form method="get" action="{% url 'posts:posts_search'%}">
<p>
<input type="text" name="q" id="id_q" value="{{ query }}" />
  <select name="categoryslug">
    {% for category in categories %}
    {% if category.parent is not None%}
        <option value="{{category.slug}}">
        {% if category.name == 'open'%}
        {{category.parent}}'s openboard
        {% endif%}
        {% if category.name == 'pro'%}
        {{category.parent}}'s professionalboard
        {% endif%}
        </option>
    {% endif%}
  {% endfor %}  
  </select>
  <input type="submit" value="Submit" /></p>
</form >
<!--search form end-->
{% for post in posts%}
<a href="{% url 'posts:posts_detail' post.id %}"><h1> {{post.title}} </h1> </a>
{{post.body | safe}}
<p>댓글수: {{post.comments_count}}</p>
{% endfor%}

<!-- 페이지 네이터-->
{%if posts.has_previous%}
<a href="?page=1">First</a>
<a href="?page={{posts.previous_page_number}}">이전</a>
{%endif%}

<span>{{posts.number}}</span>
<span>of</span>
<span>{{posts.paginator.num_pages}}</span>

{%if posts.has_next%}
<a href="?page={{posts.next_page_number}}">다음</a>
<a href="?page={{posts.paginator.num_pages}}">마지막</a>
{%endif%}
<!--페이지 네이터 부분끝-->
{% endblock %}

posts/templates/posts_my.html
{% extends 'base.html'%}

{% block title %}
<title> daemoon</title>
{% endblock %}
{% block content %}



{% for post in posts %}
<a href="{% url 'posts:posts_detail' post.id %}"><h1> {{post.title}} </h1> </a>
{% endfor %}



<!-- 페이지 네이터-->
{% if posts.has_previous %}
<a href="?page=1">First</a>
<a href="?page={{posts.previous_page_number}}">이전</a>
{% endif %}

<span>{{posts.number}}</span>
<span>of</span>
<span>{{posts.paginator.num_pages}}</span>

{%if posts.has_next%}
<a href="?page={{posts.next_page_number}}">다음</a>
<a href="?page={{posts.paginator.num_pages}}">마지막</a>
{%endif%}
<!--페이지 네이터 부분끝-->


{% endblock%}

posts/templates/posts_mycomment.html
{% extends 'base.html'%}

{% block title %}
<title> daemoon</title>
{% endblock %}
{% block content %}



{% for post in posts %}
<a href="{% url 'posts:posts_detail' post.id %}"><h1> {{post.title}} </h1> </a>
{% endfor %}



<!-- 페이지 네이터-->
{% if posts.has_previous %}
<a href="?page=1">First</a>
<a href="?page={{posts.previous_page_number}}">이전</a>
{% endif %}

<span>{{posts.number}}</span>
<span>of</span>
<span>{{posts.paginator.num_pages}}</span>

{%if posts.has_next%}
<a href="?page={{posts.next_page_number}}">다음</a>
<a href="?page={{posts.paginator.num_pages}}">마지막</a>
{%endif%}
<!--페이지 네이터 부분끝-->


{% endblock%}

posts/templates/posts_new.html
{% extends 'base.html'%}

{% block title%}
<title> daemoon</title>
{% endblock%}
{% block content %}
    <link href="/static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/dark.css" rel="stylesheet">
    <script src="/static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>


    <a href="{% url 'posts:posts_home'%}"><h1>daemoon</h1></a><br>

    <div class="container">
        <h1>글쓰기</h1>
        <hr>
        <br><br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <input type="submit" class="btn btn-dark" value="저장"/>
        </form>
    </div>

{% endblock%}