accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from . import views

Logout = LogoutView.as_view()

app_name = 'accounts'

urlpatterns = [

    path('signup/', views.UserRegistration, name = 'signup'),
    path('login/', views.UserLogin, name = 'login'),
    path('logout/', Logout, name='logout'),

    #path('resend_verify_email/', views.ResendMail, name = 'resend'),
    path('<pk>/verify/<token>/', views.UserVerification, name = 'verify'),
    
    #path('password/', views.change_password, name = 'change_password'), 
    path('user_update/', views.update_user, name = 'user_update'),
    #path('upload_profile/', views.upload_profile, name = 'upload_profile')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('sociallogin/', include('allauth.urls')),
    path('posts/',include('posts.urls',namespace="posts")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('',views.index,name="index"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from . import views


app_name = 'posts'
urlpatterns = [
    path('',views.posts_home,name='posts_home'),
    path('<int:post_id>/',views.posts_detail,name="posts_detail"),
    path('new/',views.posts_new,name="posts_new"),
    path('postslist/<str:name>/<str:slug>/',views.posts_list,name="posts_list"),
    #path('create/',views.post_create,name="post_create"),
    path('like/', views.posts_like, name='posts_like'),
    path('addcomment/<int:post_id>/',views.posts_add_comment,name='posts_add_comment'),
    path('remove/<int:comment_id>/',views.posts_remove_comment,name='posts_remove_comment'),
   # path('approve/<int:comment_id>/',views.posts_approve_comment,name='posts_approve_comment'),
    path('delete/<int:post_id>/',views.posts_delete,name='posts_delete'),
    path('edit/<int:post_id>/',views.posts_edit,name='posts_edit'),
    path('commentedit/<int:comment_id>/',views.posts_edit_comment,name="posts_edit_comment"),
    path('postssearch/',views.posts_search,name="posts_search"),
    path('mypost/',views.posts_my,name="posts_my"),
    #path('commnetlike/',views.comment_like,name='comment_like'),
]

accounts/models.py
# Create your models here.
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
import os

class UserManager(BaseUserManager) :

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields) :

        if not email :
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email = email, **extra_fields)
        user.set_password(password)
        user.save(using = self._db)

        return user

    def create_user(self, email = None, password = None, **extra_fields) :

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_expert', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields) :

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_expert', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True :
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True :
            raise ValueError('Superuser must have is_superuser=True.')
        
        return self._create_user(email, password, **extra_fields)
    
def validate_image(image):

    ext = os.path.splitext(image.name)[1]
    valid = ['.jpg', '.jpeg', '.png']
    file_size = image.file.size
    limit = 4

    if file_size > limit * 1024 * 1024:
        raise ValidationError("이미지 파일이 너무 큽니다.")
    
    if ext not in valid :
        raise ValidationError("지원하지 않는 이미지 형식입니다.")
    

class User(AbstractBaseUser, PermissionsMixin) :

    email = models.EmailField(
        verbose_name = _('Email Address'),
        max_length = 255, 
        unique = True
    )

    name = models.CharField(
        verbose_name = _('Nick Name'),
        max_length = 30,
        unique = True
    )

    profile_image = models.ImageField(
        verbose_name = _('프로필 이미지'),
        blank = True,
        null = True,
        upload_to = 'profile_image',
        default = None,
        validators = [validate_image]
    )

    is_staff = models.BooleanField(
        verbose_name = _('관리자 권한'),
        default = False
    )

    is_active = models.BooleanField(
        verbose_name = _('사용중'),
        default = False
    )

    is_expert = models.BooleanField(
        verbose_name = _('전문가'),
        default = False
    )

    date_joined  = models.DateTimeField(
        verbose_name = _('가입일'),
        default = timezone.now
    )
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    class Meta : 

        verbose_name = _('user')
        verbose_name_plural = _('users')
        swappable = 'AUTH_USER_MODEL'

    def email_user(self, subject, message, from_email=None, **kwargs) :

        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from django.forms import EmailField, EmailInput
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.db.models import EmailField
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.hashers import check_password
from django.core.exceptions import ValidationError


from .validator import RegisteredEmailValidator


class UserRegistrationForm(UserCreationForm) :

    email = forms.EmailField(required = True)
    name = forms.CharField(required = True)

    class Meta : 

        model = get_user_model()
        fields = ('email', 'name', 'profile_image')

class VerificationEmailForm(forms.Form):

    widget = forms.EmailInput(attrs={'autofocus': True})
    email = EmailField(widget, validators=(EmailField.default_validators + [RegisteredEmailValidator()]))

class CustomUserChangeForm(forms.ModelForm) :

    error_messages = {
        'password_mismatch': "변경할 비밀번호가 일치하지 않습니다.",
    }
 
    old_password = forms.CharField(
        label="Old password",
        strip=False,
        widget=forms.PasswordInput
        )

    password1 = forms.CharField(
        label="New password",
        strip=False,
        widget=forms.PasswordInput
    )

    password2 = forms.CharField(
        label="New password repeated",
        strip=False,
        widget=forms.PasswordInput
        )

    class Meta:

        model = get_user_model()
        fields = ('name', 'old_password', 'password1', 'password2', 'profile_image')

    def __init__(self, *args, **kwargs):

        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):

        return self.initial["password"]

    def clean_new_password2(self):

        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

accounts/views.py
from django import forms
from django.shortcuts import render, redirect
from django.views.generic import CreateView, FormView
from django.views.generic.base import TemplateView, View
from django.contrib import messages 
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.views import LoginView
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils.decorators import method_decorator

from config import settings
from .forms import UserRegistrationForm, VerificationEmailForm, CustomUserChangeForm
from .mixin import VerifyEmailMixin

# 유저 회원가입
class UserRegistrationView(VerifyEmailMixin, CreateView) :
    model = get_user_model()
    form_class = UserRegistrationForm
    success_url = '/'
    verify_url = '/accounts/verify/'
    template_name = 'accounts/signup.html'

    def form_valid(self, form) :
        response = super().form_valid(form)
        if form.instance :
           self.send_verification_email(form.instance)
        return response
    
UserRegistration = UserRegistrationView.as_view()

# 이메일 인증
class UserVerificationView(TemplateView) :
    model = get_user_model()
    redirect_url = '/'
    token_generator = default_token_generator

    def get(self, request, *args, **kwargs) :
        if self.is_valid_token(**kwargs) :
            messages.info(request, '인증 완료')
        else :
            messages.error(request, '인증 실패')
        return HttpResponseRedirect(self.redirect_url)
    
    def is_valid_token(self, **kwargs) :
        pk = kwargs.get('pk')
        token = kwargs.get('token')
        user = self.model.objects.get(pk = pk)
        is_valid = self.token_generator.check_token(user, token)
        if is_valid :
            user.is_active = True
            user.save()
        return is_valid

UserVerification = UserVerificationView.as_view()

# 이메일 재전송
class ResendVerifyEmailView(VerifyEmailMixin, FormView):
    model = get_user_model()
    form_class = VerificationEmailForm
    success_url = '/'
    template_name = 'accounts/resend_email.html'

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = self.model.objects.get(email = email)
        except self.model.DoesNotExist:
            messages.error(self.request, '알 수 없는 사용자 입니다.')
        else:
            self.send_verification_email(user)
        return super().form_valid(form)

ResendMail = ResendVerifyEmailView.as_view()

# 로그인
class UserLoginView(LoginView) :
    template_name = 'accounts/login.html'

    def form_invalid(self, form) :
        messages.error(self.request, '로그인에 실패하였습니다', extra_tags = 'danger')
        return super().form_invalid(form)

UserLogin = UserLoginView.as_view()

# 비밀번호 변경

#@login_required
#def change_password(request):
#    if request.method == 'POST':
#        form = PasswordChangeForm(request.user, request.POST)
#        if form.is_valid():
#            user = form.save()
#            update_session_auth_hash(request, user)  # Important!
#            messages.success(request, 'Your password was successfully updated!')
#           
#            return redirect('/')
#        else:
#            messages.error(request, 'Please correct the error below.')
#    else:
#        form = PasswordChangeForm(request.user)
#    return render(request, 'accounts/change_pw.html', {
#        'form': form
#    })

# 회원정보 변경

@login_required
def update_user(request) :

    user = get_user_model()

    if request.method == 'POST' :

        user_change_form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)

        #user_change_form.username = request.POST.get(_('name'))
        #user_change_form.old_password = request.POST.get('old_password')
        #user_change_form.password1 = request.POST.get('password1')
        #user_change_form.password2 = request.POST.get('password2')

        if user_change_form.is_valid() :
            user = user_change_form.save(commit = False)

            old_password = user_change_form.cleaned_data['old_password']
            if not user.check_password(old_password) :
                raise ValidationError("이전 비밀번호가 틀렸습니다!")

            user_change_form.clean_new_password2()

            user.name = user_change_form.cleaned_data['name']
            user.set_password(user_change_form.cleaned_data['password1'])
            
            if request.FILES.get('profile_image') :
                user.profile_image = request.FILES.get('profile_image')
            
            user.save()
            
            return redirect('/')
        
        else :

            raise ValidationError("잘못된 양식입니다.")

    else : 
        user_change_form = CustomUserChangeForm(instance = request.user)
        context = {
            'form' : user_change_form
        }

        return render(request, 'accounts/update_user.html', context)

accounts/templates/accounts/change_pw.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save changes</button>
  </form>

accounts/templates/accounts/login.html
{% load socialaccount %}
{% providers_media_js %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/2191da7206.js"></script>
  <title>Document</title>
  <style>
    * {
    margin: 0;
}

a {
    cursor: pointer;
}

input:focus, button:focus {
    outline: none;
}

::placeholder {
    color: #FFF;
    opacity: 0.5;
    font-family: 'Roboto', sans-serif;
}

::-ms-input-placeholder {
    color: #FFF;
    font-family: 'Roboto', sans-serif;
}


@keyframes bggradient {
    0% {
        background-position: 0%
    }
    100% {
        background-position: 100%
    }
}

.bgline {
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    width: 100vw;
    z-index: -1;
    background-color: #000000;
    background-position: center;
    box-sizing: border-box;
    background-size: cover;
}

.header-logo {
    width: 100%;
    height: 100px;
    float: left;
    background-color: #000000;
    margin: 30px 0 0;
    background-position: center;
    box-sizing: border-box;
    background-size: contain;
    background-repeat: no-repeat;
}
.header-desc {
    width: 100%;
    height: 95px;
    float: left;
    margin: 25px 0 10px 0;
    text-align: center;
    font-size: 1.2rem;
    font-family: 'Lato', sans-serif;
    font-weight: bold;
    font-style: italic;
    color: white;
}

.login {
    height: 100vh;
    width: 100%;
    max-width: 450px;
    margin: 0 auto;
}

.login-wrap {
    background: #000000;
    width: calc(100% - 140px);
    padding: calc(50vh - 259px)70px;
    overflow: auto;
    box-shadow: 0 12px 15px 0 rgba(0, 0, 0, .24), 0 17px 50px 0 rgba(0, 0, 0, .19);
}

#signinbox {
    display: block;
    float: left;
    margin-bottom: 114px;
}

@media (max-height: 518px) {
    #signinbox {
        margin-bottom: calc((100vh - 404px));
    }
}

#signupbox {
    display: none;
    float: left;
}

.inputfield {
    height: 20px;
    width: calc(100% - 22px);
    padding: 10px;
    font-size: 14px;
    /*border-radius: 14px;
    background: rgba(255, 255, 255, 0);*/
    background: rgba(255, 255, 255, 0);
    outline: none;
    border: none;
    border-bottom: white solid 1px;
    color: #fff;
    margin-bottom: 30px;
    font-family: 'Roboto', sans-serif;
}

.inputsubmit {
    height: 40px;
    width: 100%;
    font-size: 14px;
    border: none;
    border-radius: 3px;
    background: #000000;
  border: white solid 1px;
    text-align: center;
    color: #fff;
    cursor: pointer;
    font-family: 'Roboto', sans-serif;
    position: relative;
    overflow: hidden;
}

.inputsubmit:active {
    background: #fff;
    color: #000;
}


.y-inputsubmit {
    height: 40px;
    width: 50%;
    display: inline-block;
    float: left;
    font-size: 14px;
    border: none;
    border-radius: 3px;
    background: #000000;
  border: white solid 1px;
    text-align: center;
    color: #fff;
    cursor: pointer;
    font-family: 'Roboto', sans-serif;
    position: relative;
    overflow: hidden;
}

  </style>
</head>
<body>
  <div class="bgline"  style="background-image: url(/static/img/Main.png);"></div>
<div class="login">
    <div class="login-wrap">
        <div class="header-logo" style="background-image: url(/static/img/logo.png);">
        </div>
        <div class="header-desc">Beyond a doubt truth bears<br>
the same relation<br>
to falsehood as light to darkness.
        </div>
        <div id="signinbox">
            <form method="POST" action="{% url 'accounts:login' %}" id="signinform">
            {% csrf_token %}
                <input type = "text" name = "username" class = "inputfield" placeholder = "Username" required/>
                <input type = "password" name = "password" class = "inputfield" placeholder = "Password" required/>
                <button id = "loginsubmit" type = "submit" class = "inputsubmit">Sign In</button>
            {% if form.errors %}
            <p>로그인실패</p>
            {% endif %}
            </form>
            
            {# 지우지 마세요 #}
            <!-- <button onclick="location.href='{% url 'accounts:signup'%}' " id="loginsubmit" class="inputsubmit" style="margin-top:10px;">Create account</button> -->
            <button onclick="location.href='{% provider_login_url 'google' %}' " id="y-loginsubmit" type="submit" class="y-inputsubmit first-submit" style="margin-top:10px; text-align:center;"><i class="fab fa-google-plus-square fa-2x" style=" color:white; opacity:0.5;"></i></button>
            <button onclick="location.href='{% provider_login_url 'naver' %}' " id="y-loginsubmit" type="submit" class="y-inputsubmit third-submit" style="margin-top:10px;">naver</button>

        </div>
    </div>
</div>
</body>
</html>

accounts/templates/accounts/resend_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>인증</title>
</head>
<body>
    <div class="panel panel-default registration">
        <div class="panel-heading">
            인증이메일 보내기
        </div>
        <div class="panel-body">
            <form action="{% url 'accounts:resend' %}" method="POST">
                {% csrf_token %}
                {{form}}
            </form>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/signup.html
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/2191da7206.js"></script>
  <title>Document</title>
  <style>
    * {
    margin: 0;
}

a {
    cursor: pointer;
}

input:focus, button:focus {
    outline: none;
}

::placeholder {
    color: #FFF;
    opacity: 0.5;
    font-family: 'Roboto', sans-serif;
}

::-ms-input-placeholder {
    color: #FFF;
    font-family: 'Roboto', sans-serif;
}


@keyframes bggradient {
    0% {
        background-position: 0%
    }
    100% {
        background-position: 100%
    }
}

.bgline {
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    width: 100vw;
    z-index: -1;
    background-color: #000000;
    background-position: center;
    box-sizing: border-box;
    background-size: cover;
}

.header-logo {
    width: 100%;
    height: 100px;
    float: left;
    background-color: #000000;
    margin: 30px 0 0;
    background-position: center;
    box-sizing: border-box;
    background-size: contain;
    background-repeat: no-repeat;
}
.header-desc {
    width: 100%;
    height: 140px;
    float: left;
    margin: 10px 0 10px 0;
    text-align: center;

}

.header-profile{
  width: 140px;
  height: 140px;
  border-radius:50%;
  text-align: center;
  background-color: blue;
  margin: 0 auto;
}

.login {
    height: 100vh;
    width: 100%;
    max-width: 450px;
    margin: 0 auto;
}

.login-wrap {
    background: #000000;
    width: calc(100% - 140px);
    padding: 70px;
      overflow: hidden;
    box-shadow: 0 12px 15px 0 rgba(0, 0, 0, .24), 0 17px 50px 0 rgba(0, 0, 0, .19);
}

#signinbox {
    display: inline-block;
    float: left;
    margin-bottom: 114px;
}

@media (max-height: 518px) {
    #signinbox {
        margin-bottom: calc((100vh - 404px));
    }
}

#signupbox {
    display: none;
    float: left;
}

.inputfield {
    height: 20px;
    width: calc(100% - 22px);
    padding: 10px;
    font-size: 14px;
    /*border-radius: 14px;
    background: rgba(255, 255, 255, 0);*/
    background: rgba(255, 255, 255, 0);
    outline: none;
    border: none;
    border-bottom: white solid 1px;
    color: #fff;
    margin-bottom: 30px;
    font-family: 'Roboto', sans-serif;
}

.inputsubmit {
    height: 40px;
    width: 100%;
    font-size: 14px;
    border: none;
    border-radius: 3px;
    background: #000000;
  border: white solid 1px;
    text-align: center;
    color: #fff;
    cursor: pointer;
    font-family: 'Roboto', sans-serif;
    position: relative;
    overflow: hidden;
}

.y-inputsubmit {
    height: 40px;
    width: 50%;
    display: inline-block;
    float: left;
    font-size: 14px;
    border: none;
    border-radius: 3px;
    background: #000000;
  border: white solid 1px;
    text-align: center;
    color: #fff;
    cursor: pointer;
    font-family: 'Roboto', sans-serif;
    position: relative;
    overflow: hidden;
}
.fab .fa-facebook-square{
  color: #3b5998;
}

.mid-submit{
margin-right: 2%;
margin-left: 2%;
}

.inputsubmit:active {
    background: #fff;
    color: #000;
}
.first-submit:active{
  background: #fff;
  color: #fff;
}
.mid-submit:active{
  background: #fff;
  color: #fff;
}
.third-submit:active{
  background: #fff;
  color: #fff;
}
  </style>
</head>
<body>
  <div class="bgline"  style="background-image: url(/static/img/Main.png);"></div>
<div class="login">
    <div class="login-wrap">
        <div class="header-logo" style="color:#fff; text-align:center; vertical-align: middle; font-size: 2.5rem; font-family: 'Lato', sans-serif;">
          SIGN UP
        </div>
        <div class="header-desc">
        <div class="header-profile" type="image" style="background-position: center center;
            background-repeat: no-repeat;
            background-size: cover;
            background-origin: border-box;
            background-attachment: fixed;"></div>
        </div>
        <div id="signinbox">
            <form method="POST" action="{% url 'accounts:signup' %}" id = "signupform" enctype="multipart/form-data">
                {% csrf_token %}
                  <input type = "file" name = "profile_image"/>
                  <input type = "email" name = "email" class= "inputfield" placeholder="Email" required/>
                  <input type = "text" name = "name" class="inputfield" placeholder="Username" required/>
                  <input type = "password" name = "password1" class="inputfield" placeholder="Password" required/>
                  <input type = "password" name = "password2" class="inputfield" placeholder="Password Confirmation" required/>
                  <button id = "signupsubmit" type="submit" class="inputsubmit">Sign Up</button>
            </form>
            <div style="font-size:14px; color:#fff; opacity:0.7; margin: 0 auto; margin-top:1rem; margin-bottom:10px; text-align:center;">Or join with your social network</div>
            <button onclick="location.href='{% provider_login_url 'google' %}' " id="y-loginsubmit" type="submit" class="y-inputsubmit first-submit" style="margin-top:10px; text-align:center;"><i class="fab fa-google-plus-square fa-2x" style=" color:white; opacity:0.5;"></i></button>
            <button onclick="location.href='{% provider_login_url 'naver' %}' " id="y-loginsubmit" type="submit" class="y-inputsubmit third-submit" style="margin-top:10px;">naver</button>

        </div>
    </div>
</div>
</body>
</html>

accounts/templates/accounts/update_user.html
<form method="POST" action="{% url 'accounts:user_update' %}" id = "signinform" enctype="multipart/form-data">
  {% csrf_token %}
    <input type = "file" name = "profile_image" class="inputfield"/>
    <input type = "text" name = "name" class="inputfield" placeholder="Username" value = "{{user.name}}" required/>
    <input type = "password" name = "old_password" class="inputfield" placeholder="Current Password" required/>
    <input type = "password" name = "password1" class="inputfield" placeholder="Password" required/>
    <input type = "password" name = "password2" class="inputfield" placeholder="Password Confirmation" required/>
    <button id = "signupsubmit" type="submit" class="inputsubmit">Save</button>
</form>

accounts/templates/accounts/verification.html
<table style="box-sizing: border-box; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; width: 100%; height: 100%; background-color: rgb(234, 236, 237); font-family: Arial Black, Gadget, sans-serif;" width="100%" height="100%" bgcolor="rgb(234, 236, 237)">
    <tbody style="box-sizing: border-box;">
      <tr style="box-sizing: border-box; vertical-align: top;" valign="top">
        <td style="box-sizing: border-box;">
          <table style="box-sizing: border-box; font-family: Helvetica, serif; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; margin-top: auto; margin-right: auto; margin-bottom: auto; margin-left: auto; height: 0px; width: 90%; max-width: 550px;" width="90%" height="0">
            <tbody style="box-sizing: border-box;">
              <tr style="box-sizing: border-box;">
                <td style="box-sizing: border-box; vertical-align: top; font-size: medium; padding-bottom: 50px;" valign="top">
                  <table style="box-sizing: border-box; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; margin-bottom: 20px; height: 0px;" height="0">
                    <tbody style="box-sizing: border-box;">
                      <tr style="box-sizing: border-box;">
                        <td style="box-sizing: border-box; background-color: rgb(255, 255, 255); overflow-x: hidden; overflow-y: hidden; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; text-align: center;" bgcolor="rgb(255, 255, 255)" align="center">
                          <table style="box-sizing: border-box; width: 100%; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; height: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; border-collapse: collapse;" width="100%" height="0">
                            <tbody style="box-sizing: border-box;">
                              <tr style="box-sizing: border-box;">
                                <td style="box-sizing: border-box; font-size: 13px; line-height: 20px; color: rgb(111, 119, 125); padding-top: 10px; padding-right: 20px; padding-bottom: 0px; padding-left: 20px; vertical-align: top;" valign="top">
                                  <h1 style="box-sizing: border-box; font-size: 25px; font-weight: 300; color: rgb(68, 68, 68);">
                                    <span style="box-sizing: border-box; font-family: Arial,Helvetica,sans-serif;">가입을 환영합니다!</span>
                                  </h1>
                                  <p style="box-sizing: border-box;">
                                    <span style="box-sizing: border-box; font-family: Arial,Helvetica,sans-serif;">회원님이 가입하신 것이 맞다면 아래 "인증하기" 버튼을 눌러서 인증해주세요. 가입하신 적이 없을 경우 인증하기를 누르지 마시고 무시하세요.</span>
                                  </p>
                                  <table style="box-sizing: border-box; margin-top: 0px; margin-right: auto; margin-bottom: 10px; margin-left: auto; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; width: 100%;" width="100%">
                                    <tbody style="box-sizing: border-box;">
                                      <tr style="box-sizing: border-box;">
                                        <td style="box-sizing: border-box; padding-top: 20px; padding-right: 0px; padding-bottom: 20px; padding-left: 0px; text-align: center;" align="center">
                                          <a href="{{ url }}" class="button" style="box-sizing: border-box; font-size: 16px; padding-top: 10px; padding-right: 20px; padding-bottom: 10px; padding-left: 20px; background-color: rgb(217, 131, 166); color: rgb(255, 255, 255); text-align: center; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; font-family: Arial, Helvetica, sans-serif; font-weight: 500; text-decoration: underline;">인증하기</a>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>